name = "geminigen-proxy-ui"
main = "src/index.js"
compatibility_date = "2024-03-20"

[vars]
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzI2NTIwMDAsInN1YiI6IjIwNjZkNjdhLWYzYzQtMTFmMC1iN2Q3LWYyZjFmZTg1NzFhYyJ9.9MHzj4hAYlRtNtLg5_C1oEDesl8R0IH9c7EiKS4M7uA"
GUARD_ID = "AcMg5pPJIdeJVZtdzGnBBXABws8DyKRyVGETMJuSlMPuj-_zfFvUuySw_sU9dOXPMLYgr6osC5dfZYa6MCwLl19lhrowK_34HWWGuhFWZoIhVmaCIQ"
